/*
 * HPC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type VmItem struct {

	Id string `json:"id"`

	Since time.Time `json:"since"`

	Image string `json:"image"`
}
