/*
 * OpenHPC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimod

type VmListResp struct {

	Docker []VmListItem `json:"docker"`

	Podman []VmListItem `json:"podman"`
}
