/*
 * OpenHPC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimod

type VmReq struct {

	Provider string `json:"provider"`

	Owner string `json:"owner"`

	Project string `json:"project"`

	EnableRds bool `json:"enable_rds"`

	RdsFolder string `json:"rds_folder"`
}
