/*
 * OpenHPC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimod

type VmUpgradeReq struct {

	Id string `json:"id"`

	Shm int32 `json:"shm"`

	Provider string `json:"provider"`
}
