/*
 * OpenHPC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimod

type VmCreatedInfo struct {

	Cid string `json:"cid"`

	RdsAt string `json:"rds_at"`

	Token string `json:"token"`

	Ssh string `json:"ssh"`

	Http string `json:"http"`

	SvcTag string `json:"svc_tag"`

	Sc string `json:"sc"`
}
