/*
 * OpenHPC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimod

type VmListItem struct {

	Cid string `json:"cid"`

	Mount []VmListItemMount `json:"mount"`

	Port []VmListItemMount `json:"port"`

	SvcTag string `json:"svc_tag"`

	Sc string `json:"sc"`

	Status string `json:"status"`

	Owner string `json:"owner"`

	Project string `json:"project"`

	Image string `json:"image"`
}
