/*
 * OpenHPC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimod

type VmReqAvailResources struct {

	Images []VmReqAvailImage `json:"images"`

	Gpus []VmReqAvailGpu `json:"gpus"`

	Providers []string `json:"providers"`
}
