/*
 * OpenHPC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimod

type VmReqAvailImage struct {

	Image string `json:"image"`

	Description string `json:"description"`

	DisplayName string `json:"display_name"`
}
