/*
 * OpenHPC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimod

type VmListItemMount struct {

	Host string `json:"host"`

	Container string `json:"container"`

	Readonly bool `json:"readonly"`
}
